/* The following code was generated by JFlex 1.4.3 on 01/03/17 15:03 */

import java.util.ArrayList;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 01/03/17 15:03 from the specification file
 * <tt>lexicalAnalyzer.jflex</tt>
 */
class lexicalAnalyzer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\43\1\42\2\0\1\43\22\0\1\43\7\0\1\33\1\33"+
    "\1\41\1\40\1\33\1\40\1\3\1\41\12\1\1\34\1\33\1\36"+
    "\1\35\1\37\2\0\32\2\4\0\1\4\1\0\1\13\1\23\1\24"+
    "\1\25\1\21\1\27\1\12\1\31\1\16\2\2\1\22\1\14\1\17"+
    "\1\11\1\7\1\2\1\10\1\30\1\20\1\26\1\15\1\32\3\2"+
    "\1\5\1\0\1\6\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\1\1\3\1\4\1\2\14\3\2\4"+
    "\3\5\1\6\1\7\1\10\1\11\1\12\1\0\2\3"+
    "\1\6\3\3\1\13\7\3\1\14\2\3\1\7\21\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\220\0\264\0\330\0\374"+
    "\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0\0\u01d4\0\u01f8\0\u021c"+
    "\0\u0240\0\u0264\0\44\0\u0288\0\44\0\u02ac\0\u02d0\0\44"+
    "\0\44\0\44\0\44\0\220\0\264\0\u02f4\0\u0318\0\154"+
    "\0\u033c\0\u0360\0\u0384\0\154\0\u03a8\0\u03cc\0\u03f0\0\u0414"+
    "\0\u0438\0\u045c\0\u0480\0\44\0\u04a4\0\u04c8\0\154\0\u04ec"+
    "\0\u0510\0\u0534\0\u0558\0\u057c\0\u05a0\0\u05c4\0\u05e8\0\u060c"+
    "\0\u0630\0\u0654\0\u0678\0\u069c\0\u06c0\0\u06e4\0\u0708\0\u072c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\2\1\6\1\2\1\7"+
    "\1\10\1\11\1\4\1\12\1\4\1\13\1\14\1\15"+
    "\1\16\1\17\1\4\1\20\1\4\1\21\4\4\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\45\0\1\3\1\0\1\34\41\0\2\4\1\0"+
    "\1\4\2\0\24\4\12\0\1\34\42\0\6\35\1\33"+
    "\35\35\1\0\2\4\1\0\1\4\2\0\1\4\1\36"+
    "\22\4\12\0\2\4\1\0\1\4\2\0\12\4\1\37"+
    "\11\4\12\0\2\4\1\0\1\4\2\0\1\4\1\40"+
    "\22\4\12\0\2\4\1\0\1\4\2\0\10\4\1\41"+
    "\13\4\12\0\2\4\1\0\1\4\2\0\4\4\1\42"+
    "\17\4\12\0\2\4\1\0\1\4\2\0\10\4\1\43"+
    "\7\4\1\44\3\4\12\0\2\4\1\0\1\4\2\0"+
    "\2\4\1\45\21\4\12\0\2\4\1\0\1\4\2\0"+
    "\22\4\1\46\1\4\12\0\2\4\1\0\1\4\2\0"+
    "\10\4\1\47\2\4\1\50\10\4\12\0\2\4\1\0"+
    "\1\4\2\0\2\4\1\51\7\4\1\52\11\4\12\0"+
    "\2\4\1\0\1\4\2\0\2\4\1\44\21\4\12\0"+
    "\2\4\1\0\1\4\2\0\22\4\1\53\1\4\46\0"+
    "\1\54\43\0\1\25\1\0\1\25\41\0\1\25\7\0"+
    "\2\4\1\0\1\4\2\0\2\4\1\55\21\4\12\0"+
    "\2\4\1\0\1\4\2\0\4\4\1\56\17\4\12\0"+
    "\2\4\1\0\1\4\2\0\16\4\1\57\5\4\12\0"+
    "\2\4\1\0\1\4\2\0\1\4\1\44\22\4\12\0"+
    "\2\4\1\0\1\4\2\0\11\4\1\60\12\4\12\0"+
    "\2\4\1\0\1\4\2\0\11\4\1\44\12\4\12\0"+
    "\2\4\1\0\1\4\2\0\12\4\1\61\11\4\12\0"+
    "\2\4\1\0\1\4\2\0\16\4\1\44\5\4\12\0"+
    "\2\4\1\0\1\4\2\0\21\4\1\62\2\4\12\0"+
    "\2\4\1\0\1\4\2\0\2\4\1\63\21\4\12\0"+
    "\2\4\1\0\1\4\2\0\3\4\1\64\20\4\12\0"+
    "\2\4\1\0\1\4\2\0\7\4\1\65\14\4\12\0"+
    "\2\4\1\0\1\4\2\0\3\4\1\66\11\4\1\67"+
    "\6\4\12\0\2\4\1\0\1\4\2\0\13\4\1\44"+
    "\10\4\12\0\2\4\1\0\1\4\2\0\12\4\1\70"+
    "\11\4\12\0\2\4\1\0\1\4\2\0\10\4\1\44"+
    "\13\4\12\0\2\4\1\0\1\4\2\0\12\4\1\44"+
    "\11\4\12\0\2\4\1\0\1\4\2\0\13\4\1\71"+
    "\10\4\12\0\2\4\1\0\1\4\2\0\7\4\1\61"+
    "\14\4\12\0\2\4\1\0\1\4\2\0\13\4\1\62"+
    "\10\4\12\0\2\4\1\0\1\4\2\0\1\4\1\72"+
    "\22\4\12\0\2\4\1\0\1\4\2\0\12\4\1\73"+
    "\11\4\12\0\2\4\1\0\1\4\2\0\3\4\1\74"+
    "\20\4\12\0\2\4\1\0\1\4\2\0\12\4\1\75"+
    "\11\4\12\0\2\4\1\0\1\4\2\0\4\4\1\76"+
    "\17\4\12\0\2\4\1\0\1\4\2\0\16\4\1\77"+
    "\5\4\12\0\2\4\1\0\1\4\2\0\12\4\1\42"+
    "\11\4\12\0\2\4\1\0\1\4\2\0\4\4\1\61"+
    "\17\4\12\0\2\4\1\0\1\4\2\0\5\4\1\44"+
    "\16\4\12\0\2\4\1\0\1\4\2\0\17\4\1\100"+
    "\4\4\12\0\2\4\1\0\1\4\2\0\1\4\1\62"+
    "\22\4\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1872];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\1\11\20\1\1\11\1\1\1\11\2\1\4\11"+
    "\1\1\1\0\16\1\1\11\24\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[64];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	int line = 1;
	boolean isOK = true;
	ArrayList<String> output = new ArrayList<String>();
	ArrayList<String> error_log = new ArrayList<String>();	


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  lexicalAnalyzer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  lexicalAnalyzer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 108) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    	if(isOK){
		for(int i = 0; i < output.size(); i++){
			System.out.println(output.get(i));
		}
	}else{
		System.out.println("Falha na análise do arquivo");
		for(int i = 0; i < error_log.size(); i++){
			System.out.println(error_log.get(i));
		}
	}

    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 12: 
          { output.add(yytext() + " | Comando de atribuição | Linha "+ line);
          }
        case 13: break;
        case 4: 
          { output.add(yytext() + " | Delimitador | Linha "+ line);
          }
        case 14: break;
        case 5: 
          { output.add(yytext() + " | Operador relacional | Linha "+ line);
          }
        case 15: break;
        case 6: 
          { output.add(yytext() + " | Operador aditivo | Linha "+ line);
          }
        case 16: break;
        case 10: 
          { output.add(yytext() + " | Número real | Linha "+ line);
          }
        case 17: break;
        case 3: 
          { output.add(yytext() + " | Identificador | Linha "+ line);
          }
        case 18: break;
        case 2: 
          { isOK = false; error_log.add("Erro na linha "+ line +" - "+ yytext());
          }
        case 19: break;
        case 8: 
          { line++;
          }
        case 20: break;
        case 7: 
          { output.add(yytext() + " | Operador multiplicativo | Linha "+ line);
          }
        case 21: break;
        case 11: 
          { output.add(yytext() + " | Palavra reservada | Linha "+ line);
          }
        case 22: break;
        case 9: 
          { 
          }
        case 23: break;
        case 1: 
          { output.add(yytext() + " | Número inteiro | Linha "+ line);
          }
        case 24: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java lexicalAnalyzer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        lexicalAnalyzer scanner = null;
        try {
          scanner = new lexicalAnalyzer( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
